# Generated by Django 2.1.15 on 2024-02-28 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'comment_reply',
                'ordering': ['reply_time'],
            },
        ),
        migrations.CreateModel(
            name='HistoryTradeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_price', models.FloatField()),
                ('trade_quantity', models.IntegerField()),
                ('trade_dateTime', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'history_trade_table',
            },
        ),
        migrations.CreateModel(
            name='ManageTable',
            fields=[
                ('manage_id', models.CharField(max_length=12)),
                ('manage_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('photo_url', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'manage_table',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('source', models.URLField(null=True)),
                ('content', models.TextField()),
                ('news_dataTime', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='StockComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(verbose_name='股票内容')),
                ('comment_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_comment',
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('stock_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=45)),
                ('issuance_time', models.CharField(max_length=45)),
                ('closing_price_y', models.FloatField(null=True)),
                ('open_price_t', models.FloatField(null=True)),
                ('stock_type', models.CharField(max_length=15, null=True)),
                ('block', models.CharField(max_length=45, null=True)),
                ('change_extent', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'stock_info',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.CharField(max_length=12)),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('user_sex', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('photo_url', models.CharField(max_length=45)),
                ('account_balance', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.AddField(
            model_name='stockcomment',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialSystem.StockInfo'),
        ),
        migrations.AddField(
            model_name='stockcomment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialSystem.UserTable'),
        ),
        migrations.AddField(
            model_name='historytradetable',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialSystem.StockInfo'),
        ),
        migrations.AddField(
            model_name='historytradetable',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialSystem.UserTable'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialSystem.StockComment'),
        ),
    ]
