USE financial_platform;

INSERT INTO news (title, source, content, news_dataTime) VALUES ('Another air strike killed 6 people!', 'CCTV Finance', 'According to reports from Iraqi National Television, after senior Iranian Islamic Revolutionary Guard General Soleimani and others were killed in a US air strike, the capital Baghdad was once again hit by a US air strike on the evening of the 3rd local time. The airstrike killed six people and seriously injured three others. On the same day, Iran stated that it would retaliate against the United States at the "appropriate time and place" and that the United States must bear all consequences for this.', '2024-03-02');

INSERT INTO news (title, source, content, news_dataTime) VALUES ('Global shock! After Iranian Major Ge', 'Brokerage China', 'Based on news from major media, on January 3, local time, General Qasem Soleimani, commander of the Iranian Islamic Revolutionary Guard Corps’ “Quds Force”, was killed in an air strike near Baghdad Airport in Iraq. The U.S. Pentagon stated that U.S. President Trump ordered the "killing" of General Soleimani, commander of the Iranian Islamic Revolutionary Guard Corps' , '2024-03-02');

INSERT INTO news (title, source, content, news_dataTime) VALUES ('The conflict between the United States', 'Brokerage China', 'The conflict between the United States and Iran triggered concerns in the crude oil market. The two major international oil prices, the United States and Burundi, once rose by more than 4% during the day, and domestic crude oil and fuel futures both rose by nearly 4%. As soon as the news came out, oil stocks moved during the session, with Zhongman Petroleum closing the market in a straight line, and other potential stocks such as Hengxin, Petrochemical Oil Services, and Bakken Energy all rose sharply.', '2024-03-02');

INSERT INTO news (title, source, content, news_dataTime) VALUES ('The cumulative net inflow is 1 trillion', 'China Securities Journal', 'On the first trading day of 2024, A-shares are off to a good start! On January 2, the major A-share stock indexes collectively rose sharply. The Shanghai Composite Index once approached 3,100 points during the session. The Shenzhen Component Index and the ChiNext Index rose nearly 2%. The total turnover of the two cities was 751.5 billion yuan. The net inflow of northbound funds on that day exceeded 10 billion yuan. As of the close of trading on January 2, since the opening of the Shanghai-Shenzhen-Hong Kong Stock Connect, the cumulative net inflow of northbound funds exceeded one trillion yuan, reaching 1,003.6 billion yuan.', '2024-03-02');

INSERT INTO news (title, source, content, news_dataTime) VALUES ('Institutional market discussion: The r', NULL, 'At the closing of Thursday, we pointed out that the market will form a certain rest trend on Friday. This is indeed the case for the whole day of the market on Friday. There is no obvious way to approach the stock index. At the same time, the trading volume has also shrunk significantly, and the characteristics of a slight rest are more obvious. This week\'s market is a New Year\'s Eve market price period. It is a link between the past and the next, and the key time period shows an obvious profit-making effect. As far as next week is concerned, it is expected that next week it will rise and fall back to consolidate and rest, or it will be directly consolidated and rested.', '2024-03-02');

INSERT INTO news (title, source, content, news_dataTime) VALUES ('Institutional market discussion: The', NULL, 'In 2024, the new securities law will be officially implemented, the GEM reform is on the horizon, incremental funds are coming from all sources, and the allocation continues to be optimistic about the certainty of economic improvement. For high-end technology and securities firms, in terms of operation, it is recommended to continue to pay attention to blue-chip and technology growth stocks at the bottom, do not chase high, and grasp the rhythm.', '2024-03-02');

INSERT INTO news (title, source, content, news_dataTime) VALUES ('800 billion big profit! The central', 'Securities Times', 'Statistics show that after the central bank announced reserve requirement ratio cuts, the rise and fall of A-shares the next day were basically the same. Judging from the 18 central bank RRR cuts in history, a total of 8 times the Shanghai Stock Index rose the next day and 10 times it closed down.', '2024-03-02');

INSERT INTO news (title, source, content, news_dataTime) VALUES ('Central Bank: Lower the deposit rese', 'Central Bank', 'In order to support the development of the real economy and reduce the actual cost of social financing, the People\'s Bank of China decided to lower the deposit reserve ratio of financial institutions by 0.5 percentage points on January 6, 2024. percentage points (excluding finance companies, financial leasing companies and automobile finance companies).', '2024-03-02');

INSERT INTO news (title, source, content, news_dataTime) VALUES ('Review 2023! Understand the bullis', NULL, 'Will A-shares be prosperous in 2023? The Shenzhen Stock Exchange Component Index’s increase ranks second in the world! We use 32 pictures to review 2023 with you and reminisce about the bits and pieces that made us excited.', '2024-03-02');
